[package]
authors = ["OKP4"]
edition = "2021"
name = "okp4-logic-bindings"
version = "1.0.0"

[dependencies]
cosmwasm-std.workspace = true
form_urlencoded = "1.1.0"
schemars.workspace = true
serde-json-wasm.workspace = true
serde.workspace = true
thiserror.workspace = true
url = "2.3.1"
