[package]
authors = ["OKP4"]
edition = "2021"
name = "okp4-objectarium-client"
version = "2.1.0"

[dependencies]
cosmwasm-std.workspace = true
okp4-logic-bindings.workspace = true
okp4-objectarium.workspace = true
schemars.workspace = true
serde.workspace = true
